FROM python:3.8.10-alpine
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD [ "python3", "github-api/main.py" ]



# FROM python:3.10-alpine
# WORKDIR /app
# COPY . .
# RUN pip install -r requirements.txt
# EXPOSE 5000
# CMD ["python3", "/app/github-api/app.py"]