apiVersion: apps/v1
kind: Deployment
metadata:
  name: sp-challenge-flask-deployment
  namespace: sailpoint
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sp-challenge-app
  template:
    metadata:
      labels:
        app: sp-challenge-app
    spec:
      containers:
      - name: sp-challenge-app
        image: amarchandran/sp-challenge:1.0.0-latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000