apiVersion: v1
kind: Service
metadata:
  name: sp-challenge-flask-service
  namespace: sailpoint
spec:
  selector:
    app: sp-challenge-app
  ports:
  - port: 5000
    targetPort: 5000
  type: LoadBalancer